config/routes.rb
Rails.application.routes.draw do

  # Initial page
  root 'pages#home'

  # Users
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks'  }
  get '/timeline' => 'users#timeline', as: :timeline
end

app/models/autorization.rb
class Autorization < ActiveRecord::Base

	belongs_to :user
	after_create :fetch_details
	def fetch_details
		self.send("fetch_details_from_#{self.provider.downcase}")
	end


	def fetch_details_from_linkedin
	end

end

app/models/identity.rb
class Identity < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :uid, :provider
	validates_uniqueness_of :uid, :scope => :provider

	def self.find_for_oauth(auth)
		find_or_create_by(uid: auth.uid, provider: auth.provider)
	end
end

app/models/user.rb
require 'open-uri'
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,:omniauthable,:omniauth_providers => [:linkedin]

  # FriendlyID Gem
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [:name,
      [:name, :id]
    ]
  end
  # end

  # PaperClip + Dropbox
  has_attached_file :image,:styles => {
    :large => "512x512" ,
    :medium => "200x200" ,
    :small => "168x168",
    :thumb => "40x40",
    :tiny => "32x32"
    },
    :default_url => :set_default_url,
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    :path =>  "/images/users/:id-:basename.:style.:extension",
    :dropbox_options => {}
    validates_attachment :image,
    :content_type => { :content_type => ["image/jpg", "image/gif", "image/png","image/jpeg",] },
    :size => { :in => 0..6144.kilobytes }

    # if user dont have image
    def set_default_url
      "img/missing.png"
    end
  # End --- 


  # Linkedin oauth
  def skip_confirmation!
    self.confirmed_at = Time.now.utc
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)
      # Get the identity and user if they exist
      identity = Identity.find_for_oauth(auth)
      # If a signed_in_resource is provided it always overrides the existing user
      # to prevent the identity being locked with accidentally created accounts.
      # Note that this may leave zombie accounts (with no associated identity) which
      # can be cleaned up at a later date.
      user = signed_in_resource ? signed_in_resource : identity.user
      # Create the user if needed
      if user.nil?
        # Get the existing user by email if the provider gives us a verified email.
        # If no verified email was provided we assign a temporary email and ask the
        # user to verify it on the next step via UsersController.finish_signup
        email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
        email = auth.info.email
        name = auth.info.name
        headline = auth.info.headline
        location = auth.info.location
        image_linkedin = auth[:extra][:raw_info][:pictureUrls][:values].first
        url_linkedin = auth.info.urls.public_profile

        #Open a new file in referential folder to upload at dropbox
        open(image_linkedin) {|f|
          File.open("public/images/social_user.jpg","wb") do |file|
            file.puts f.read
          end
        }
        # Open local folder/file to save
        image = open('public/images/social_user.jpg')

        # Create the user if it's a new registration
        if user.nil?
        	unless image_linkedin
        		image_linkedin = "http://startupculture.com.br/img/user_missing.png"
        	end
        	user = User.new(
        		name: name,
        		image_linkedin: image_linkedin,
            image:  image,
            headline: headline,
            location: location,
            url_linkedin: url_linkedin,
            email: email,
            password: Devise.friendly_token[0,20]

            )
        	user.skip_confirmation!
        	user.save!
          # Drop created file after save on db/dropbox
          system("cd public/images && rm -rf social_user.jpg")
        end
      end
      # Associate the identity with the user if needed
      if identity.user != user
        identity.user = user
        identity.save!
      end
        user
    end
    def email_verified?
      #self.email && self.email !~ TEMP_EMAIL_REGEX
    end
    # ---- Linkedin Oauth End


    # This trick user dont need repeat current_password to create a new password.
    def update_with_password(params={}) 
    	if params[:password].blank? 
    		params.delete(:password) 
    		params.delete(:password_confirmation) if params[:password_confirmation].blank? 
    	end 
    	update_attributes(params) 
    end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	helper_method :current_user

  
	before_filter :configure_devise_params, if: :devise_controller?
	def configure_devise_params
		devise_parameter_sanitizer.for(:sign_up) do |u|
	    	u.permit(:name,:email,:password,:password_confirmation,:image_linkedin)
	    end
	    devise_parameter_sanitizer.for(:account_update) do |u|
	    	u.permit(:name,:email,:password,:url_linkedin,:url_facebook,:password_confirmation, :image,:image_file_name, :image_content_type, :image_file_size,:headline)
	    end
	end

  
	def after_sign_in_path_for(resource)
  		case resource
        	when User
        		then 
        			timeline_path
     			else 
        			root_path
    	end
	end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def self.provides_callback_for(provider)
    class_eval %Q{
      def #{provider}
        @user = User.find_for_oauth(env["omniauth.auth"], current_user)

        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    }
  end

  [:facebook, :linkedin].each do |provider|
    provides_callback_for provider
  end

  def after_sign_in_path_for(resource)
    case resource
      when User
        then root_path
      when Admin
          then system_index_path
      else 
          root_path
      end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_core, only: [:show, :edit, :update, :destroy]

	def timeline
		@user = current_user
	end

	def set_core
		@user = User.friendly.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
      :count => resource.errors.count,
      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <strong>#{sentence}</strong>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Culture</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :modernizr %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= yield %>

<footer class="footer">
  <div class="container">
    <p><%= link_to icon('github'),root_path,:class => 'text-muted' %> | © StartupCulture</p>
  </div>
</footer>
</body>
</html>

app/views/navbars/_home.html.erb
<%= javascript_include_tag 'animatedHeader' %>
<!-- Navigation -->
<nav class="navbar navbar-home navbar-fixed-top">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header page-scroll">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand page-scroll" href="/"><%= icon('rocket') %> StartupCulture</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li class="hidden">
					<a href="#page-top"></a>
				</li>
				<li>
					<a class="page-scroll" href="#services">Cadastrar</a>
				</li>
				<li>
					<a class="page-scroll" href="/users/sign_in">Entrar</a>
				</li>
			</ul>
		</div>
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container-fluid -->
</nav>

app/views/navbars/_user.html.erb
 <!-- Fixed navbar -->
 <nav class="navbar navbar-user navbar-fixed-top" role="navigation">
   <div class="container">
     <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <%= link_to "#{icon('rocket')} StartupCulture".html_safe,timeline_path,:class => "navbar-brand" %>
     </div>
     <div id="navbar" class="navbar-collapse collapse">
       <ul class="nav navbar-nav">
       </ul>
       <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= current_user.name %>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li>Oi</li>
            <li><%# link_to 'Cadastar empresa',cadastro_empresa_path %></li>
            <li class="divider"></li>
            <li class="dropdown-header">Meu cadastro</li>
            <li><%= link_to current_user.name,edit_user_registration_path %></li>
            <li><%# link_to "Editar meu cadastro",alterar_cadastro_path(current_user) %></li>
            <li><%# link_to "Mensagens",usuario_mensagens_path %></li>
            <li><%= link_to "Sair", destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
        <% end %>
       </ul>
       <%= image_tag current_user.image.url(:tiny),:class => 'nav navbar-nav navbar-right navbar-profile-image',:alt=> "user image" %>
     </div><!--/.nav-collapse -->
   </div>
 </nav>

app/views/pages/home.html.erb
<%= render 'navbars/home' %>

<section class="homepage-header">
	<div class="container intro">
		<div class="row">
			<div class="col-lg-12 col-md-12col-sm-12 col-xs-12">
				<h1>Ecossistema de startups do Brasil</h1>
				<h3>A rede social do empreendedor</h3>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
				<h3>457</h3>
				<h4 class="reposition">Startups</h4>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
				<h3>610</h3>
				<h4 class="reposition">Empreendedores</h4>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
				<h3>9</h3>
				<h4 class="reposition">Núcleos</h4>
			</div>
		</div>
	</div>
</section>

<section class="homepage-howit">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h2>Mais de R$<strong>10.000,00</strong> investidos online este mês </h2>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
				<%= icon('briefcase fa-5x') %>
				<h3>Vagas</h3>
				<p>As oportunidades nas melhores startups da sua região</p>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
				<%= icon('users fa-5x') %>
				<h3>Perfis</h3>
				<p>O perfil completo das startups e dos empreendedores</p>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
				<%= icon('globe fa-5x') %>
				<h3>Nucleos</h3>
				<p>Tenha o mapa, as startups da sua região e fomente o ecossistema local</p>
			</div>
		</div>
	</div>
</section>
<section class="homepage-midia">
	<h2>Culture na mídia<h2>
	<%= link_to image_tag('/img/midia/catracalivre.png'),'https://catracalivre.com.br/geral/negocio-urbanidade/indicacao/projeto-mapeia-atividade-empreendedora-no-brasil/',target: "_blank"  %>
	<%= link_to image_tag('/img/midia/wide.png'),'http://revistawide.com.br/tecnologia/publique-sua-startup',target: "_blank"  %>
	<%= link_to image_tag('/img/midia/startup_stars.png'),'http://revistawide.com.br/tecnologia/publique-sua-startup',target: "_blank"  %>
	<%= link_to image_tag('/img/midia/draft.png'),'http://projetodraft.com/selecao-draft-organizando-a-informacao/',target: "_blank"  %>
</div>
</section>

<section class="homepage-partners">
	<h2>Nossos parceiros</h2>
	<%= link_to image_tag('/img/partners/digital_ocean.png'),'https://www.digitalocean.com/?refcode=365573b9f27b',target: "_blank"  %>
	<%= link_to image_tag('/img/partners/negocio_mulher_menor.png'),'http://negociodemulher.com.br/',target: "_blank"  %>
	<%= link_to image_tag('/img/partners/mailee_me.png'),'https://www.mailee.me/pt',target: "_blank"  %>
	<%= link_to image_tag('/img/partners/insper.png'),'http://www.insper.edu.br/?gclid=Cj0KEQiA7tCjBRDulMny5rfM0dkBEiQA7fcshbfCxZTQEvhW7qfMW8LRpWLBRZNuBPEO4hbf-p_-0jQaAsOe8P8HAQ',target: "_blank"  %>
	<%= link_to image_tag('/img/partners/startupGarage2.png'),'http://startupgarage.com.br',target: "_blank"  %>
	<%= link_to image_tag('/img/partners/zendesk_logo.png'),'https://www.zendesk.com.br/produto',target: "_blank"  %>
	<%= link_to image_tag('/img/partners/contaAzul.png'),'https://contaazul.com/como-funciona',target: "_blank"  %>
	<%= link_to image_tag('/img/partners/plug.png'),'http://plug.ae/',target: "_blank"  %>
</section>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Entrar", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
 <%= link_to "Cadastrar", new_registration_path(resource_name) %> <br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu a senha?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %>
<% end -%>

app/views/users/timeline.html.erb
<%= render 'navbars/user' %>
<div class="container">
	<div class="row">
		<div class="col-sm-3">
			<div class="row">
				<div class="col-sm-6">
					<%= image_tag @user.image.url(:small),:class => "thumbnail user-timeline-profile" %>
				</div>
				<div class="col-sm-6">
					<strong><%= current_user.name %></strong>
					<p><%= link_to "Editar perfil", edit_user_registration_path  %>
					</div>
				</div>
				<ul class="list-group">
					<%= link_to "#{icon('newspaper-o')} Feed de Notícias".html_safe,timeline_path,:class=>"list-group-item" %>
					<%= link_to "#{icon('comments-o')} Mensagens".html_safe,timeline_path,:class=>"list-group-item" %>
					<%= link_to "#{icon('building-o ')} Minhas Startups".html_safe,timeline_path,:class=>"list-group-item" %>
				</ul>


				<ul class="list-group">
					<%= link_to "#{icon('user')} Empreendedores".html_safe,timeline_path,:class=>"list-group-item" %>
					<%= link_to "#{icon('rocket')} Startups".html_safe,timeline_path,:class=>"list-group-item" %>
					<%= link_to "#{icon('users')} Núcleos".html_safe,timeline_path,:class=>"list-group-item" %>
					<%= link_to "#{icon('globe')} Mapa".html_safe,timeline_path,:class=>"list-group-item" %>
					<%= link_to "#{icon('briefcase')} Vagas".html_safe,timeline_path,:class=>"list-group-item" %>
				</ul>

			</div>
			<div class="col-sm-7">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="row">
							<div class="col-sm-1">
								<%= image_tag @user.image.url(:tiny),:class => "timeline-tiny-image" %>
							</div>
							<div class="col-sm-4">
								<strong><%= current_user.name %></strong><br />
								<small class="text-muted">Example block-level</small>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>